### ISSUE TITLE
advert not showing on iOS

### ISSUE THREAD

**Issue by odejinmi** [pavelzaichyk/flutter_unity_ads#13]
unity advert not showing on the iOS device, it is not showing any error

**Comment by pavzay** [comment]
@odejinmi provide more information.
is ad shown in test mode?

**Comment by tdncreative** [comment]
@pavzay The ads closed after 1 sec

**Comment by tdncreative** [comment]
E/UnityAds: -[UADSAVPlayer observeValueForKeyPath:ofObject:change:context:] (line:273) :: VIDEOPLAYER_ERROR: Error Domain=AVFoundationErrorDomain Code=-11800 "The operation could not be completed" UserInfo={NSLocalizedFailureReason=An unknown error occurred (-12746), NSLocalizedDescription=The operation could not be completed, NSUnderlyingError=0x600001bfdce0 {Error Domain=NSOSStatusErrorDomain Code=-12746 "(null)"}}
E/UnityAds: +[USRVApiSdk WebViewExposed_logError:callback:] (line:60) :: Unity Ads video player generic error file:///Users/"macName"/Library/Developer/CoreSimulator/Devices/DF4787DE-419B-4FEA-BA48-5CF3DB0D52AE/data/Containers/Data/Application/B7EB9179-6722-4A8C-899D-19218CF162DD/Library/Caches/UnityAdsCache-ed7af4c405188b9bf037a63dcca57d982116d72d66c07483334693fd643b61d3.mp4 Error Domain=AVFoundationErrorDomain Code=-11800 "The operation could not be completed" UserInfo={NSLocalizedFailureReason=An unknown error occurred (-12746), NSLocalizedDescription=The operation could not be completed, NSUnderlyingError=0x600001bfdce0 {Error Domain=NSOSStatusErrorDomain Code=-12746 "(null)"}}
I/UnityAds: +[USRVApiSdk WebViewExposed_logInfo:callback:] (line:70) :: Closing Unity Ads ad unit

**Comment by tdncreative** [comment]
Banner Ads also doesn't work

**Comment by tdncreative** [comment]
Update: this error only showed up when you are trying to run the app on iOS simulator inside virtualbox. Outside that is fine :D

**Comment by odejinmi** [comment]
> @odejinmi provide more information.
> is ad shown in test mode?

it is not also show in test mode

**Comment by odejinmi** [comment]
> Update: this error only showed up when you are trying to run the app on iOS simulator inside virtualbox. Outside that is fine :D

I'm using simulator
