### ISSUE TITLE
New Unity Mediation (Beta)! 

### ISSUE THREAD

**Issue by Riyaz7364** [pavelzaichyk/flutter_unity_ads#16]
Hey, I'm using unity ads on my Flutter apps. Can you please provide me with SDK installation for Flutter?

Currently, I'm using this Fluter package on my all projects https://pub.dev/packages/unity_ads_plugin

Please provide an updated version...

**Comment by noaldocruz** [comment]
does it support  https://pub.dev/packages/unity_ads_plugin  new unity mediation? I wannt try but I'm not sure about that.

**Comment by pavzay** [comment]
unity_ads_plugin does not support new Unity Mediation yet

**Comment by minhdev2017** [comment]
you can use it: https://github.com/minhdev2017/flutter_unity_mediation
note: not work with firebase_store, I must to replace it by firebase_database
