### ISSUE TITLE
Keep isAdReady parameter

### ISSUE THREAD

**Issue by anass-naoushy** [pavelzaichyk/flutter_unity_ads#22]
I usually load rewarded ads when the user enters an article to read and then when he exits is I show him the ad. But how can I know that the ad is ready and has fully loaded. I cannot use the parameters of onComplete... bcz I am loading the Ad in a separate page from where the user is shown the Ad.

**Comment by pavelzaichyk** [comment]
`isReady` is removed from Unity Ads SDK  with comment `Use the updated Load method signature to access load callbacks.` https://docs.unity.com/ads/DeprecatedAPIClasses.htm
