### ISSUE TITLE
Custom data privacy and consent

### ISSUE THREAD

**Issue by cristian1980** [pavelzaichyk/flutter_unity_ads#24]
Please help in supporting custom data privacy and consent schemes.
Bellow is a link with what functionality we should be able to access from flutter:

https://docs.unity3d.com/Packages/com.unity.ads@3.4/manual/LegalDataPrivacy.html

**Comment by pavelzaichyk** [comment]
You can try this in the new version `0.3.2`. 
https://pub.dev/packages/unity_ads_plugin#privacy-consent
