### ISSUE TITLE
No fill for placement ...

### ISSUE THREAD

**Issue by SwiftyFlow** [pavelzaichyk/flutter_unity_ads#27]
Same as when I do iOS only development, but the it eventually shows.

Now on a flutter project, iOS side give me the usual "No fill for placement ..." error. Even if I think I've done more than enough...

Error:
E[/UnityAds](): +[USRVApiSdk WebViewExposed_logError:callback:] (line:60) :: No fill for placement banner001
flutter: Banner Ad banner001 failed: UnityAdsBannerError.noFill message: Placement banner001 failed to fill!

Implementation:

class _MainScreenState extends State<MainScreen> {
  final bool _showBanner = true; //fixme: ads: in-app purchase

  @override
  void initState() {
    super.initState();

    UnityAds.init(
      gameId: AdManager.gameId,
      testMode: false,
      onComplete: () {},
      onFailed: (error, message) {},
    );
  }

@override
  Widget build(BuildContext context) {

return Scaffold(
[...]
body: Column(
children: <Widget>[
[...]
if (_showBanner)
            SizedBox(
              width: 375,
              height: 60,
              child: UnityBannerAd(
                placementId: AdManager.bannerAdPlacementId,
                onLoad: (placementId) => print('Banner loaded: $placementId'),
                onClick: (placementId) => print('Banner clicked: $placementId'),
                onFailed: (placementId, error, message) => print(
                    'Banner Ad $placementId failed: $error message: $message'),
              ),
            ),
],
),
}
}
}

class AdManager {
  static String get gameId {
    if (defaultTargetPlatform == TargetPlatform.android) {
      return 'xxx';
    }
    if (defaultTargetPlatform == TargetPlatform.iOS) {
      return 'xxx';
    }
    return '';
  }

  static String get bannerAdPlacementId {
    if (defaultTargetPlatform == TargetPlatform.android) {
      return 'Android_Banner';
    }
    if (defaultTargetPlatform == TargetPlatform.iOS) {
      return 'banner001';
    }
    return '';
  }
}

**Comment by SwiftyFlow** [comment]
Notice I give it a SizedBox of more than it needs... I tried without, I tried the proper size (320x50) but nothing makes it work.

I then remembered needing to add the UnityAds.framework in the root of iOS to make it work in the past. No change.

Got my allow tracking request ✅

Got my plist ads provider list ✅

It was working with the test ads but when I turn them properly ON it doesn't - Apple rejection for displaying a test banner 🤦🏻‍♂️

What to do?

**Comment by SwiftyFlow** [comment]
Re-pushing as is hoping it will resolve all alone like it does when I do iOS only...

I definitely suspect the store ID to be a thing that put us all in trouble.

**Comment by elgsylvain85** [comment]
Facing same issue with only banner in production, test banner working correctly

**Comment by FlorentPottevin** [comment]
I lodged a complaint and the answer was to try a vpn to US or Asia as there is probably no banner to be delivered in Europe at the moment. I haven’t tried yet. But this more than an unsatisfactory answer. Why I’m using UnityAds? And why do they ask the mediation thing? Then you answer they are your only provider and you get no banner. Great service

**Comment by gadgetreviews** [comment]
I added following lines after UnityAds.init, but still no fill at European countries. Any solution for this problem?
```
      await UnityAds.setPrivacyConsent(PrivacyConsentType.gdpr, true);
      await UnityAds.setPrivacyConsent(PrivacyConsentType.ageGate, true);
      await UnityAds.setPrivacyConsent(PrivacyConsentType.ccpa, true);
      await UnityAds.setPrivacyConsent(PrivacyConsentType.pipl, true);
```

**Comment by FlorentPottevin** [comment]
On a break, will get back to you shortly (still not working hey not much exiting news…)

**Comment by SwiftyFlow** [comment]
Got an answer saying:
"Since you are testing in Europe you are likely not seeing banners due as you have failed to respond to or trigger the GDPR consent dialogue box. The consent dialogue is displayed the first time the SDK is requested to show an interstitial or rewarded ad. Unfortunately as such it is required to show at least one non-banner ad in your application for banners to function in countries that require GDPR."


Answered:
This got me curious as I am asking for GDPR consent. (like you)
So I've added just for fun the firing of an interstitial when the banner fails to load and a video shows perfectly fine...
Now I have a video ad' on app opening which will be granting me of a nice apple store rejection hahaha.
Does this info help? Or should I accept that there is no banner in Europe ATM?

**Comment by SwiftyFlow** [comment]
Now do you ask on iOS via the appDelegate?

**Comment by gadgetreviews** [comment]
Thanks for information. This information might be helpful for me. In fact I am planning UnityAds for only android version <= 9. I am planning to continue to use admob on iOS and android version >= 10.

I can try to load an interstitial ad after several pages once for android < 10 devices. Google may not reject this way.

**Comment by gadgetreviews** [comment]
By the way, if I will show consent screen to EU users, no one will accept to see ads. I am planning to sell ad-free version with in app purchase and they can simply reject consent and get ad-free version with free. :)

**Comment by SwiftyFlow** [comment]
Interesting.. However to me, they are not refusing ads, they are refusing to be tracked (which is only here to give them more interesting ads...) at least that's what I thought. But people, they on the other hand, think we will sale their data to a demon so... Being banned from adMod I might start begging in real life rather than online. Because anyway 0.0005c an ad this is just "begging 1.0"

**Comment by gadgetreviews** [comment]
I am considering UnityAds for android version <= 9 because admob has a huge performance impact for android <= 9. I started not to show admob for android <= 9, than started to think showing UnityAds for android <= 9. But because of poor income, maybe it is not worth to code for unityAds. Because android >= 10 devices will get more and more share in time.

On the other I tried to show an Interstitial ad and I noticed that there is an Opt Out of Personalized Network-Wide button. I guess this means, that device should be opt in for personalized ads. But I still don't see any banner ads. What I am missing?

**Comment by emielvandeveire** [comment]
I'm also facing this exact problem. Has anyone found a solution or is it better to switch to admob?

**Comment by JohanJimenex** [comment]
> I'm also facing this exact problem. Has anyone found a solution or is it better to switch to admob?

Some news ? I have the same problem in Unity Engine

**Comment by Abdulah-butt** [comment]
facing same issue
