### ISSUE TITLE
Google Play complains about SDK and advertiser ID

### ISSUE THREAD

**Issue by mikron123** [pavelzaichyk/flutter_unity_ads#31]
![image](https://user-images.githubusercontent.com/16115860/184127260-bb7a3879-803a-4461-9e61-62c6a1968872.png)

I'm using version 0.3.3 (WORKS WITH VERSION 4.0.1 OF THE UNITY ADS SDK)

What am I doing wrong?
Thanks

**Comment by pavelzaichyk** [comment]
Check this thread https://forum.unity.com/threads/unityads-4-x-is-required-by-google-but-its-not-listed-in-package-manager.1302480/ and the article https://docs.unity.com/ads/GoogleDataSafety.html

**Comment by mikron123** [comment]
> Check this thread https://forum.unity.com/threads/unityads-4-x-is-required-by-google-but-its-not-listed-in-package-manager.1302480/ and the article https://docs.unity.com/ads/GoogleDataSafety.html

How does this help if this plugin still doesn't contain the necessary code? The first link is assuming you're using the native unity plugin, no?
My app is "Made for families" it is not allowed to transmit the advertiser ID at all. Is there a way to switch that parameter off?
