### ISSUE TITLE
Fail to show production Ads

### ISSUE THREAD

**Issue by HugoB07** [pavelzaichyk/flutter_unity_ads#36]
Hello,
When I use test mode, the banner ads work perfectly, but when I use production ads, the ads dont show.
I have an error : "Unity Ads was not able to get current network type due to missing permission", and "No fill placement"

Do you have any idea ?
Thanks

**Comment by tushar-foyer** [comment]
Hey @HugoB07 were you able to resolve this issue?

**Comment by HugoB07** [comment]
Hello, no, i switched to Google ads
