### ISSUE TITLE
SDK 4.6.1 is now available. Update now to increase your impression and revenue opportunities.

### ISSUE THREAD

**Issue by ashishpipaliya** [pavelzaichyk/flutter_unity_ads#37]
Can you please implement this ?
this is a screenshot from unity dashboard
![image](https://user-images.githubusercontent.com/32923529/231658055-05896aee-2d55-4eca-b183-a84e2ab456b0.png)

**Comment by pavelzaichyk** [comment]
Version 0.3.8 of the unity_ads_plugin now includes the 4.6.1 Unity Ads SDK.
