### ISSUE TITLE
Load Failed [PLACEMENT_ID]: UnityAdsLoadError.invalidArgument adMarkup is missing; objectId is missing

### ISSUE THREAD

**Issue by kkjk1176** [pavelzaichyk/flutter_unity_ads#40]
I don't know what's wrong.

**Error log**
---
```
flutter: UnityAds Load Failed [PLACEMENT_ID]: UnityAdsLoadError.invalidArgument adMarkup is missing; objectId is missing
flutter: Video Ad [PLACEMENT_ID] failed: UnityAdsShowError.notReady Placement not ready
```

**UnityDoc**
---
<img width="754" alt="스크린샷 2023-06-13 오후 4 59 43" src="https://github.com/pavelzaichyk/flutter_unity_ads/assets/47656746/7b83c145-4928-4c43-bc59-9c936f0c22dd">
<img width="759" alt="스크린샷 2023-06-13 오후 5 00 11" src="https://github.com/pavelzaichyk/flutter_unity_ads/assets/47656746/32097a79-20b5-41ac-9f2c-a110258fe40c">

**Code**
---
```
class AdsWidget extends ConsumerState<AdsWidget> with WidgetsBindingObserver {

  late final String rewardedAdsId;

  @override
  void initState() {
    super.initState();
    WidgetsBinding.instance.addObserver(this);

    rewardedAdsId = Platform.isAndroid ? Env.UNITY_ADS_REWARDED_AD_UNIT_ID_AOS : Env.UNITY_ADS_REWARDED_AD_UNIT_ID_IOS;

    UnityAds.init(
      gameId: Platform.isAndroid ? Env.UNITY_ADS_GAME_ID_AOS : Env.UNITY_ADS_GAME_ID_IOS,
      testMode: true,
      onComplete: () async {
        await UnityAds.setPrivacyConsent(PrivacyConsentType.gdpr, true);
        await UnityAds.setPrivacyConsent(PrivacyConsentType.ageGate, true);
        await UnityAds.setPrivacyConsent(PrivacyConsentType.ccpa, true);
        await UnityAds.setPrivacyConsent(PrivacyConsentType.pipl, true);
        print('[ UnityAds Initialization Complete! ]');
      },
      onFailed: (error, msg) => ('[ UnityAds Initialization Failed ] : $error | $msg'),
    );
  }

...

  @override
  Widget build(BuildContext context) {

    return TapScaleAnimation(
       ...
      onTap: () async{

          await UnityAds.load(
              placementId: rewardedAdsId,
              onComplete: (placementId) => print('UnityAds Load Complete $placementId'),
              onFailed: (placementId, error, message) => print('UnityAds Load Failed $placementId: $error $message'),
            );

            await UnityAds.showVideoAd(
              placementId: rewardedAdsId,
              onStart: (placementId) => print('Video Ad $placementId started'),
              onClick: (placementId) => print('Video Ad $placementId click'),
              onSkipped: (placementId) => print('Video Ad $placementId skipped'),
              onComplete: (placementId) => print('Video Ad $placementId completed'),
              onFailed: (placementId, error, message) => print('Video Ad $placementId failed: $error $message'),
            );
      },
      child: AnimatedSize(
        ...
}
```

**Used IDs**
---
<img width="855" alt="스크린샷 2023-06-13 오후 4 53 53" src="https://github.com/pavelzaichyk/flutter_unity_ads/assets/47656746/96e6142a-f6b3-476c-b7d7-67f3f1226d39">

**Comment by HosseinArabbeigi** [comment]
Any update here?

**Comment by icodelifee** [comment]
New project > use only unity ads options, mediation one wont work

**Comment by Us3rL0sT** [comment]
are you sure it worked? I couldn 't just install unity ads , the problem remained

**Comment by AyoubSmina** [comment]
any progress ??!

**Comment by Us3rL0sT** [comment]
I start use appodeal, so try it too. there easy to connect unity and others



> any progress ??!

**Comment by AyoubSmina** [comment]
Thanks, @Us3rL0sT I figured out a solution for that bug. I updated the Unity package from version 4.9.1 to the latest one, 4.9.2. The code is available on my repository: 
[unity_ads_plugin repository](https://github.com/AyoubSmina/unity_ads_plugin)

**Comment by AyoubSmina** [comment]
> I start use appodeal, so try it too. there easy to connect unity and others
> 
> > any progress ??!

Thanks, @Us3rL0sT I figured out a solution for that bug. I updated the Unity package from version 4.9.1 to the latest one, 4.9.2. The code is available on my repository: 
[unity_ads_plugin repository](https://github.com/AyoubSmina/unity_ads_plugin)
