### ISSUE TITLE
Build release failed on Android

### ISSUE THREAD

**Issue by felipecastro2607** [pavelzaichyk/flutter_unity_ads#41]
When i am build a release version of my app, the building process is return the following:

 flutter build apk --split-per-abi

Font asset "MaterialIcons-Regular.otf" was tree-shaken, reducing it from 1645184 to 1028 bytes (99.9% reduction). Tree-shaking can be disabled by providing the --no-tree-shake-icons flag when building your app.

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':unity_ads_plugin:verifyReleaseResources'.
> A failure occurred while executing com.android.build.gradle.tasks.VerifyLibraryResourcesTask$Action
   > Android resource linking failed
     ERROR:/Users/felipe/Desktop/dukitan/split_test/build/unity_ads_plugin/intermediates/merged_res/release/values/values.xml:161: AAPT: error: resource android:attr/lStar not found.

* Try:
> Run with --stacktrace option to get the stack trace.
> Run with --info or --debug option to get more log output.
> Run with --scan to get full insights.

* Get more help at https://help.gradle.org

BUILD FAILED in 14s
Running Gradle task 'assembleRelease'...                           14,6s
Gradle task assembleRelease failed with exit code 1

I got this error in two apps that are working properly before. So, i tried to create a fresh new app. Made build release without any package and worked. After, a added the last version of the package (0.3.9) and then the error occurred again.

Anybody knows how to resolve this issue ?

**Comment by pavelzaichyk** [comment]
Please check `0.3.10` version

**Comment by felipecastro2607** [comment]
Problem solved! Thank you.
