### ISSUE TITLE
Banner ads not working even in test mode, Interstitial work fine

### ISSUE THREAD

**Issue by ahmedatef286** [pavelzaichyk/flutter_unity_ads#47]
Hello, 

Thank you for this awesome package, 

i have an issue that is driving me nuts. Banner ads absolutely refuse to work even when enabling test mode in code, and forcing all devices to run test ads from unity hub. Banner ads just fail to load with the no fill error (Banner Ad Banner_Android failed: UnityAdsLoadError.noFill Placement receives no fill) i think. I've triple checked my code, i added app-ads.txt in unity and still this cursed banner refuses to work.

Interstitial and video work absolutely fine, only banner ads are making me suffer.

Any help would be greatly appreciated

**Comment by Abdulah-butt** [comment]
same issue

**Comment by Abdulah-butt** [comment]
Did you fixed that?

**Comment by ahmedatef286** [comment]
No sadly. I have contacted the support and gave them the apk and logs, they are trying to find out why that happens now.
