### ISSUE TITLE
No implementation found for method init on channel com.rebeloid.unity_ads

### ISSUE THREAD

**Issue by dimasarestuprasmanto** [pavelzaichyk/flutter_unity_ads#52]
**Describe the bug**
This error only when --release mode and version 0.3.15 or  0.3.14

```
E/flutter (32434): [ERROR:flutter/runtime/dart_vm_initializer.cc(41)] Unhandled Exception: MissingPluginException(No implementation found for method init on channel com.rebeloid.unity_ads)
E/flutter (32434): #0      MethodChannel._invokeMethod (package:flutter/src/services/platform_channel.dart:332)
E/flutter (32434): <asynchronous suspension>
E/flutter (32434): #1      UnityAds.init (package:unity_ads_plugin/src/unity_ads.dart:34)
E/flutter (32434): <asynchronous suspension>
```

**Comment by frevostudios** [comment]
The same problem.
Rollback to version 0.3.13, but the problem still occurs

      Fatal Exception: io.flutter.plugins.firebase.crashlytics.FlutterError: MissingPluginException(No implementation found for method init on channel com.rebeloid.unity_ads) at MethodChannel._invokeMethod(platform_channel.dart:332) at UnityAds.init(unity_ads.dart:34)

**Comment by frevostudios** [comment]
Another topic with the same problem: 
https://github.com/pavelzaichyk/flutter_unity_ads/issues/56

**Comment by pavelzaichyk** [comment]
Duplicate https://github.com/pavelzaichyk/flutter_unity_ads/issues/56
