### ISSUE TITLE
Could not resolve io.insert-koin:koin-bom:3.5.3 - BUG

### ISSUE THREAD

**Issue by fsmdeveloper** [pavelzaichyk/flutter_unity_ads#53]
**Flutter SDK version: 3.22.0**

Could not resolve all files for configuration ':app:debugRuntimeClasspath'.
 Could not resolve io.insert-koin:koin-bom:3.5.3.
     Required by:
         project :app
         project :app > project :unity_ads_plugin > com.unity3d.ads:unity-ads:4.11.2
       No matching variant of io.insert-koin:koin-bom:3.5.3 was found. The consumer was configured to find a library for use during runtime, preferably optimized for Android, as well as attribute 'com.android.build.api.attributes.BuildTypeAttr' with value 'debug', attribute 'com.android.build.api.attributes.AgpVersionAttr' with value '8.3.0', attribute 'org.jetbrains.kotlin.platform.type' with value 'androidJvm' but:
          - Variant 'apiElements' capability io.insert-koin:koin-bom:3.5.3:
              - Incompatible because this component declares a platform for use during compile-time and the consumer needed a library for use during runtime
              - Other compatible attributes:

                  - Doesn't say anything about its target Java environment (preferred optimized for Android)
                  - Doesn't say anything about org.jetbrains.kotlin.platform.type (required 'androidJvm')
          - Variant 'enforcedRuntimeElements' capability io.insert-koin:koin-annotations-bom-derived-enforced-platform:1.3.0 declares a component for use during runtime:
              - Incompatible because this component declares an enforced platform and the consumer needed a library
              - Other compatible attributes:
                  - Doesn't say anything about com.android.build.api.attributes.AgpVersionAttr (required '8.3.0')
                  - Doesn't say anything about com.android.build.api.attributes.BuildTypeAttr (required 'debug')
                  - Doesn't say anything about its target Java environment (preferred optimized for Android)
                  - Doesn't say anything about org.jetbrains.kotlin.platform.type (required 'androidJvm')
          - Variant 'runtimeElements' capability io.insert-koin:koin-annotations-bom:1.3.0 declares a component for use during runtime:
              - Incompatible because this component declares a platform and the consumer needed a library
              - Other compatible attributes:
                  - Doesn't say anything about com.android.build.api.attributes.AgpVersionAttr (required '8.3.0')
                  - Doesn't say anything about com.android.build.api.attributes.BuildTypeAttr (required 'debug')
                  - Doesn't say anything about its target Java environment (preferred optimized for Android)
                  - Doesn't say anything about org.jetbrains.kotlin.platform.type (required 'androidJvm')

**Comment by iZenrix** [comment]
Same issue

**Comment by cts-cts** [comment]
I'm facing the same issue! please fix the issue!

**Comment by iZenrix** [comment]
I downgraded Gradle, and the error disappeared.

from:
```
android/gradle/wrapper/gradle-wrapper.properties:
distributionUrl=https\://services.gradle.org/distributions/gradle-8.4-all.zip
```
```
android/build.gradle:
classpath 'com.android.tools.build:gradle:8.3.2'
```

to:
```
android/gradle/wrapper/gradle-wrapper.properties:
distributionUrl=https\://services.gradle.org/distributions/gradle-8.0-bin.zip
```
```
android/build.gradle:
classpath 'com.android.tools.build:gradle:8.1.3'
```
