### ISSUE TITLE
Urgent issue on production release

### ISSUE THREAD

**Issue by pyaehein** [pavelzaichyk/flutter_unity_ads#54]
I received a warning on the Play Store release. Please upgrade to the latest SDK.

![error](https://github.com/pavelzaichyk/flutter_unity_ads/assets/9808854/03027fe1-1968-4ab4-8e84-933b5e69a162)

**Comment by pavelzaichyk** [comment]
The 0.3.16 version of the Unity Ads plugin, which uses version 4.11.3 of the SDK, has been released.
