### ISSUE TITLE
MissingPluginException(No implementation found for method init on channel com.rebeloid.unity_ads)

### ISSUE THREAD

**Issue by ArZHa03** [pavelzaichyk/flutter_unity_ads#56]
**Describe the bug**
[ERROR:flutter/runtime/dart_vm_initializer.cc(41)] Unhandled Exception: MissingPluginException(No implementation found for method init on channel com.rebeloid.unity_ads)

**Details**

1. pubspec.yaml:  `unity_ads_plugin: ^0.3.16`
2. android/app/build.gradle: (depencies) 
`implementation 'com.ironsource.adapters:unityadsadapter:4.3.39'`
`implementation 'com.unity3d.ads:unity-ads:4.11.3'`
3. android/app/scr/main/AndroidManifest.xml: (permission)
`<uses-permission android:name="com.google.android.gms.permission.AD_ID"/>`
4. Unity init:
![image](https://github.com/pavelzaichyk/flutter_unity_ads/assets/106745041/676419f4-1158-470e-9ca9-631d0712c831)

**Comment by kim-mini6** [comment]
I have the same problem. Is there a solution?

**Comment by ArZHa03** [comment]
> I have the same problem. Is there a solution?

dont have, after update version ... the problem just arrived.
Before 0.3.16 version, i was work perfectly.

**Comment by frevostudios** [comment]
The same problem. 
Rollback to version 0.3.13, but the problem still occurs


`      Fatal Exception: io.flutter.plugins.firebase.crashlytics.FlutterError: MissingPluginException(No implementation found for method init on channel com.rebeloid.unity_ads)
       at MethodChannel._invokeMethod(platform_channel.dart:332)
       at UnityAds.init(unity_ads.dart:34)`

**Comment by josemangandid** [comment]
I solved like this
`    buildTypes {
        release {
            minifyEnabled false
            proguardFiles getDefaultProguardFile('proguard-android.txt'), 'proguard-rules.pro'
        }
    }`

**Comment by pavelzaichyk** [comment]
Adding `shrinkResources false` and `minifyEnabled false` to the `/android/app/build.gradle` file resolves the problem.

```gradle
android {
...
    buildTypes {
        release {
            // TODO: Add your own signing config for the release build.
            // Signing with the debug keys for now, so `flutter run --release` works.
            signingConfig signingConfigs.debug

            shrinkResources false
            minifyEnabled false
        }
    }
}
```
