### ISSUE TITLE
UnityAds.init does not work

### ISSUE THREAD

**Issue by appDevel1234** [pavelzaichyk/flutter_unity_ads#57]
Hi, thanks for this very great package!

For some days now I have the problem, that initializing unity ads does not work anymore on android devices. On iOS is everything working fine.

This is the code (`...` are just placeholders):

```
UnityAds.init(
        gameId: Platform.isAndroid ? '...' : '...',
        testMode: appIsInTestMode,
        onComplete: () => ...,
        onFailed: (error, errorMessage) => ...,
      );
```

Neither `onComplete` or `onFailed` is called, when I run `UnityAds.init`. It makes no different, if `testMode` is enabled or not. I use version 0.3.17 of the package and had the same problem in the version 0.3.9, which I used before.

`UnityAds.isInitialized()` returns false.

If I try to load an ad, then I got following error message:

`Field loadTimeoutMs_ for f7.w1 not found. Known fields are [private int f7.w1.e, private int f7.w1.f, private int f7.w1.g, private static final f7.w1 f7.w1.m, private static volatile p5.z0 f7.w1.n]`

Does anyone has an idea, what the problem could be?

Flutter doctor:

```
Doctor summary (to see all details, run flutter doctor -v):
[✓] Flutter (Channel stable, 3.13.7, on macOS 14.0 23A344 darwin-arm64, locale de-DE)
[✓] Android toolchain - develop for Android devices (Android SDK version 32.1.0-rc1)
[✓] Xcode - develop for iOS and macOS (Xcode 15.0)
[✓] Chrome - develop for the web
[✓] Android Studio (version 2022.1)
[✓] VS Code (version 1.69.2)
[✓] Connected device (4 available)
[✓] Network resources

• No issues found!
```

**Comment by pavelzaichyk** [comment]
Hi, check this solution
https://github.com/pavelzaichyk/flutter_unity_ads?tab=readme-ov-file#getting-unhandled-exception-missingpluginexceptionno-implementation-found-for-method-init-on-channel-comrebeloidunity_ads-when-running-the-application-on-android-in-release-mode
