### ISSUE TITLE
UnityAds.init() failing in release mode

### ISSUE THREAD

**Issue by Kabilan21** [pavelzaichyk/flutter_unity_ads#59]
Unity ads is not getting initialized in release mode with below exception stack trace

`PlatformException(error, Field loadTimeoutMs_ for q6.b2 not found. Known fields are [private int q6.b2.s, private int q6.b2.t, private int q6.b2.u, private static final q6.b2 q6.b2.v, private static volatile f5.z0 q6.b2.w], null, java.lang.RuntimeException: Field loadTimeoutMs_ for q6.b2 not found. Known fields are [private int q6.b2.s, private int q6.b2.t, private int q6.b2.u, private static final q6.b2 q6.b2.v, private static volatile f5.z0 q6.b2.w]
I/flutter ( 9112):      at f5.u0.r0(MessageSchema.java:7)
I/flutter ( 9112):      at f5.u0.X(MessageSchema.java:52)
I/flutter ( 9112):      at f5.u0.V(MessageSchema.java:2)
I/flutter ( 9112):      at f5.j0.e(ManifestSchemaFactory.java:13)
I/flutter ( 9112):      at f5.j0.a(ManifestSchemaFactory.java:13)
I/flutter ( 9112):      at f5.c1.c(Protobuf.java:3)
I/flutter ( 9112):      at f5.c1.d(Unknown Source:4)
I/flutter ( 9112):      at f5.y.L(GeneratedMessageLite.java:1)
I/flutter ( 9112):      at f5.y$a.r(GeneratedMessageLite.java:3)
I/flutter ( 9112):      at f5.y$a.q(GeneratedMessageLite.java:1)
I/flutter ( 9112):      at q6.f.a(Unknown Source:2)
I/flutter ( 9112):      at com.unity3d.services.core.di.UnityAdsModule.getDefaultAdOperations(UnityAdsModule.kt:5)`

**Comment by kitet** [comment]
Was about to implement then saw this issue. Anyone experiencing the same? I am between a rock and a hard place.
