### ISSUE TITLE
After showVideoAd in Flutter unity ads plugin

### ISSUE THREAD

**Issue by Anas547** [pavelzaichyk/flutter_unity_ads#8]
onTap: () {
                UnityAds.showVideoAd(
                  placementId: AdManager.interstitialVideoAdPlacementId,
                  listener: (state, args) =>
                      print('Interstitial Video Listener: $state => $args'),
                );
                Navigator.push(
                    context,
                    PageTransition(
                        child: MyWeaponArt(),
                        type: PageTransitionType.topToBottom));
              },

i call ads like this and i initialize unity only 1 time in initstate

@override
  void initState() {
    // TODO: implement initState
    super.initState();
    UnityAds.init(
      gameId: AdManager.gameId,
      listener: (state, args) => print('Init Listener: $state => $args'),
    );
  }
after show ad i close ad then application restart why???

**Comment by pavzay** [comment]
the problem isn't reproduced
@Anas547 provide more information: logs, operating system, device info, etc.
